lib-network-measurement added
ekanek/android-network-measurement-lib pull request #1
Opened 2020-08-20 06:45 UTC by pkpardeep482

2020-08-21 23:12 UTC, chandranshu12 requested changes
All work in these classes is happening on the main thread. We agreed that this will be done on a separate thread – didn't see that happening.

2020-08-21 23:12 UTC, chandranshu12 commented on README.md
> +[![](https://jitpack.io/v/ekanek/android-network-measurement-lib.svg)](https://jitpack.io/#ekanek/android-network-measurement-lib)
This is not a documentation. Please use README.md to describe how this lib should be used.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/build.gradle
> +apply plugin: 'com.android.library'
See comments in the android-device-measurement repo.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/androidTest/java/in/foxy/lib_network_measurement/ExampleInstrumentedTest.java
> +package in.foxy.lib_network_measurement;
See comments in the device-measurement repo.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/test/java/in/foxy/lib_network_measurement/ExampleUnitTest.java
> +package in.foxy.lib_network_measurement;
See the comment in the other repo.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/INetworkMonitor.java
> +
1. Where is this interface supposed to be used?
2. The method names and their parameters are not making any sense. Why'd a method named isNetworkAvailable accept a boolean? Its return type should be boolean.

Add Javadocs for this class to make sense. Also, event handlers or event listeners names should be onXXX where XXX is an event name. So, ```isNetworkAvailable``` will need to be renamed as ```onNetworkAvailabilityChange```.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +public class NetworkInfo
Not a great choice of name given that you're dependent on another class with the same name in Android stack. Why can't it be named ```DiagnosticNetworkInfo``` or ```DetailedNetworkInfo``` or ...?

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +
Why so much space?

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +    public static String getSimCardName(Context context){
No Javadoc? What does this method return - Airtel or AD1 or ...? What does it expect in parameters? A good javadoc will document an example code too.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +            network_name = "wifi";
These should be declared as enums: https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                case TelephonyManager.NETWORK_TYPE_GSM: // api<25: replace by 16
Looks like this code was copied from ```https://stackoverflow.com/questions/2802472/detect-network-connection-type-on-android?rq=1```. Please read all the answers there and also use your own grey matter. We need to support API level 16. Now, think what needs to be done here.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                    break;
Add case 20 for 5G also. Why leave it out.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +        return level;
1. This is useful for displaying bars on the device but for actual event logging, the RSSI value should be used directly. We can also check the RSSI value directly to see if it's good for video conferencing – we'll need -60 dB to -65 dB.
2. Also, `getScanResults()` seems to return much more interesting data including information on radio and distance from wifi which we should capture as well.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.onSignalStrengthChange(signalStrength.getLevel());
1. Why does our monitor use a method named `onSignalStrengthChange` when the actual standard method is named `onSignalStrengthsChanged`?
2. Also, how will you report the signalStrength in the initial net_info event since your callback will get fired only if the signal strength changes.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.isNetworkAvailable(true);
`onAvailable` is a better choice than `isNetworkAvailable`.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +            }
Where are our callbacks?

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.ipAddress(""+linkProperties.getLinkAddresses().get(0));
This callback (again name) is getting called even if the IP address had not changed but some other property.

2020-08-21 23:12 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.onUploadSpeed(""+networkCapabilities.getLinkUpstreamBandwidthKbps());
1. What is the need to make two different method calls? Just use one callback to pass both download and upload speeds.
2. Why are you converting the ints to Strings?

2020-08-21 23:46 UTC, chandranshu12 requested changes
1. Use this to get IP location: @https://www.googleapis.com/geolocation/v1/geolocate?key=@. Talk to Naved if needed.
2. Use SubscriptionManager as described here with several examples: https://stackoverflow.com/questions/22170425/get-operator-details-for-dual-sim-android-phone to get a list of all providers on multi-sim devices.
3. You've neither crossed out Frequency & Radio, nor detected it. Frequency information is available in `WifiManager.getScanResults()`
4. Use https://developer.android.com/reference/android/telephony/CellSignalStrength to get ASU, Dbm and level when not on Wifi. The technology-specific classes such as https://developer.android.com/reference/android/telephony/CellSignalStrengthCdma have a method named getEvdoSnr to return SNR for cellular networks. This method is different for different classes.

2020-08-21 23:46 UTC, chandranshu12 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +        return telephonyManager.getSimOperatorName();
This is not complete. Use SubscriptionManager as described here with several examples: https://stackoverflow.com/questions/22170425/get-operator-details-for-dual-sim-android-phone to get a list of all providers on multi-sim devices.

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/androidTest/java/in/foxy/lib_network_measurement/ExampleInstrumentedTest.java
> +package in.foxy.lib_network_measurement;
Removed file

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/test/java/in/foxy/lib_network_measurement/ExampleUnitTest.java
> +package in.foxy.lib_network_measurement;
removed

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +public class NetworkInfo
Using DetailedNetworkInfo

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/INetworkMonitor.java
> +
Doc added

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +    public static String getSimCardName(Context context){
Removed this method and added proper method to find details of multiple sims

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +        return level;
Scan results provide same information which we can retrieve from WifiInfo

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.onSignalStrengthChange(signalStrength.getLevel());
removed this method, no need of this

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.ipAddress(""+linkProperties.getLinkAddresses().get(0));
removed

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +                iNetworkMonitor.onUploadSpeed(""+networkCapabilities.getLinkUpstreamBandwidthKbps());
fixed

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/src/main/java/in/foxy/lib_network_measurement/NetworkInfo.java
> +            }
onBlockedStatusChanged removed, added callback to onLosing

2020-08-23 13:07 UTC, pkpardeep482 commented on lib-network-measurement/build.gradle
> +        minSdkVersion 22
Most of the Classes were added in API level 22, and even i cannot think of any use case where we will support < android 5.1

2020-08-25 12:26 UTC, chandranshu12 approved these changes
Giving up on formatting. Will sit with you to get your AndroidStudio settings done.

2020-08-25 12:26 UTC, merged